# Use Node.js as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the app's source code to the container
COPY . .

# Environment variables
ENV PORT 3000
ENV REACT_APP_API_BASE http://localhost:3001

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]